### ISSUE TITLE
Release for support virtual environment

### ISSUE THREAD

**Issue by hbkshawn** [KxSystems/embedPy#104]
Hi team,

We recently tried to use embedPy in projects. However, we need to use in Python virtual environment. Tested with latest release 1.3.8, not working.

Looks like a recent commit in May 2021 added this support. Is there an official release then?

Thanks and regards,
Shawn

**Comment by cmccarthy1** [comment]
Hi Shawn,

That has now been updated with release `1.4.0`. Note that this functionality is only provided for Linux and OSX installations at this time.

Please let us know if there are any issues and open this issue again or open a new issue outlining any problems you might find.

Regards,

Conor

**Comment by hbkshawn** [comment]
is there an update for windows in the future?

**Comment by cmccarthy1** [comment]
I'm unsure of that at present, Windows venvs work quiet differently to Linux/OSX and work that we've done to this point hasn't provided with us a path that will allow us to support each of these so we don't have a timeline on when/if we can support them.

**Comment by hbkshawn** [comment]
thanks for your explanation. looking forward to this feature.
