### ISSUE TITLE
Cannot pass the test.q when installing from Win release

### ISSUE THREAD

**Issue by amRsching** [KxSystems/embedPy#107]
I'm installing embedPy from a windows release.
According to the instructions, I need to run the tests in the unzipped directory. However I cannot pass the test with the following error log.

...\embedPy-1.4.1> q test.q
KDB+ 4.0 2021.07.12 Copyright (C) 1993-2021 Kx Systems
w64/ 16(16)core 32620MB ...

'The specified module could not be found.
  [5]  C:\Users\ma-pi\Downloads\embedPy-1.4.1\embedPy-1.4.1\p.q:12:
 `L`M`H`P`B set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];.P.env:not H~P;
 .p:(`:./p 2:(`init;3))[L;H;B]]
           ^
q.p))

My python version 3.8.8, KDB version 4.0, OS Win10.
It seems I missed some packages. Could anyone tell me what package or module I missed?
Thank you.

**Comment by cmccarthy1** [comment]
It doesn't appear that you have copied the appropriate `*.dll` file into `%QHOME%/w64`, If you download `embedPy_windows-1.3.8.zip`  you should be able to copy `w64/p.dll` to `%QHOME%/w64` and `p.q` to `%QHOME%`. The `1.4.1` release is missing the windows build.

Alternatively you can install via conda using
```
conda install -c kx embedpy
```
This is the method we recommend

**Comment by amRsching** [comment]
> It doesn't appear that you have copied the appropriate `*.dll` file into `%QHOME%/w64`, If you download `embedPy_windows-1.3.8.zip` you should be able to copy `w64/p.dll` to `%QHOME%/w64` and `p.q` to `%QHOME%`. The `1.4.1` release is missing the windows build.
> 
> Alternatively you can install via conda using
> 
> ```
> conda install -c kx embedpy
> ```
> 
> This is the method we recommend

Thank you very much. Because in the installation instructions, running q test.q is before copying files to %QHOME% directories, I didn't copy them. And you are right, for windows users, we should download Version 1.3.8 instead of 1.4.1. I have solved my problem with your advice.
