### ISSUE TITLE
Install fails on redhat 2.6 x86_64

### ISSUE THREAD

**Issue by MaxHoefl** [KxSystems/embedPy#39]
Hi,

I followed the installation steps [here](https://github.com/kxsystems/embedpy) (using embedPy release 1.1 for linux) but when I load `p.q` I get an error

```
{"'",x,"'.join([__import__('sysconfig').get_config_var(v)for v in",ssr[.j.j y;"\"";"'"],"])"}
'.j.j
```
I am using anaconda 4.5.0, have copied p.q and p.k into $QHOME/ and p.so into $QHOME/l64/ and set the environment variable `LD_LIBRARY_PATH` (to `/home/hoeflm/anaconda3/lib`)

**Comment by MaxHoefl** [comment]
I am using `KDB+ 3.0 2012.05.29`

**Comment by jhanna-kx** [comment]
Hi,
You'll need to use at least version 3.5 (64-bit only) in order to use embedPy, can you try upgrading to see if that resolves the issue ?
Thanks

**Comment by MaxHoefl** [comment]
yes that resolved the issue, thanks. Another catch is that embedPy was probably built for RHEL 7, so RHEL 6 users have to install glibc-2.14 manually, see (here) [https://unix.stackexchange.com/questions/439445/glibc-install-from-source-doesnt-create-lib-folder/439446#439446]
