### ISSUE TITLE
Why need setting `LD_LIBRARY_PATH` with conda python?

### ISSUE THREAD

**Issue by lwshang** [KxSystems/embedPy#42]
To have _embedPy_ work with conda python on Linux, we have to set `LD_LIBRARY_PATH`.
This looks like a temporary work around and may cause several issue when we using other softwares.

Why this setting is needed? Which part of _embedPy_ request it?

I'm asking this question because I want to help solve it. _embedPy_ may not be good enough to be used in production with this issue.

**Comment by jhanna-kx** [comment]
This is an issue as anaconda packages libraries which may conflict with the (system) versions loaded by q at startup (e.g. libssl or libz). There is an conda packaged version of q which doesn't require this now, if you are already using anaconda then you can install it with

`conda install -c kx kdb`

**Comment by lwshang** [comment]
Got it. I've started using `conda` to install kdb and embedPy since kx25. It's really convenient.
