### ISSUE TITLE
Lists of objects aren't being unwrapped recursively?

### ISSUE THREAD

**Issue by mcg1969** [KxSystems/embedPy#44]
I was playing with some advanced IPython widget usage that requires passing in lists whose first element is a Python object. Unfortunately, while bare Python objects are automatically unwrapped on the way back to Python, that's not true of Python objects in a _list_. I did discover that you can force them to be unwrapped, but it seems better if the embedPy functionality would do this recursively on lists and other composite objects.
```
p)class MyObject:
    pass
p)def bar():
    return MyObject()
p)def foo(x):
    if isinstance(x, list):
        print('[' + (', '.join(repr(y) for y in x)) + ']')
    else:
        print(repr(x))
foo:.p.get[`foo]
bar:.p.get[`bar]
foo(bar[])
foo((bar[];1))
foo((bar[]`.;1))
foo("a";1)
```
Output:
```
<__main__.MyObject object at 0x1196b2f98>
[<built-in method q) of PyCapsule object at 0x1155632d0>, 1]
[<__main__.MyObject object at 0x1196b2f98>, 1]
['a', 1]
```
What seems sensible is that the to have to use that back-tick notation, so that the second line behaves the way the third one does.

**Comment by awilson-kx** [comment]
Hey Michael

This was a design/performance decision, as recursive type checking proved too expensive.

When passing arguments using embedPy
- A native q object will be converted as appropriate (int -> int, float-array -> float-array)
- An embedPy object will be unwrapped (exposing the foreign Python object)

Unwrapping of embedPy objects inside q 'containers' (lists, dictionaries, tables etc) will not take place by default.
In most cases, no conversion is even necessary (as the argument consists solely of q data) and the performance hit is too great.

**Comment by jhanna-kx** [comment]
Added `.p.xunwrap` to do this recursive unwrap in [1.2.0](../releases/1.2.0) release
