### ISSUE TITLE
datetime convertion for matplotlib

### ISSUE THREAD

**Issue by sitsang** [KxSystems/embedPy#49]
I found that it isn't possible to plot the date axis using embedPy, because it is not sending the datetime as python datetime object when embedPy convert the Q object to python object.  You can run this under JupyterQ:

```
\l p.q
\d .matplotlib
isroutine:.p.import[`inspect;`:isroutine];
getmembers:.p.import[`inspect;`:getmembers];
wrapm:{[x]
 names:getmembers[x;isroutine]`;
 res:``_pyobj!((::);x);
 res,:(`$names[;0])!{.p.wrap x 1}each names;
 res}
pyplot:{wrapm .p.import`matplotlib.pyplot}

plt:.matplotlib.pyplot[];
x:.z.T+til 10;
y:til 10;
plt.plot[x;y];

plt.show[];
```

The x axis is expected to be a time, but it is render as a number

**Comment by jhanna-kx** [comment]
Hi,
Temporal types are converted to the underlying integers when converting to python as python and q temporal types don't line up in an obvious way, python `datetime.datetime` doesn't seem like a natural conversion for q `time` to me as there is no date component to a q `time`,  `datetime.timedelta` might be closer (although precisions are different).
 
In your case as matplotlib won't accept `timedelta`, you can create `datetime` with a meaningless date component, one way to do that is:

```q
todatetime:{x . {(`year`mm`dd`hh`uu`ss$x),(x mod"j"$1e9)div 1000}.z.D+y}[.p.import[`datetime;`:datetime;>]]

x:todatetime each .z.T+til 10;
```
