### ISSUE TITLE
support RHEL6 ?

### ISSUE THREAD

**Issue by juanez** [KxSystems/embedPy#54]
RHEL6 is still widely used in the banking world, would be nice if you had pre-built binaries for that version too.

**Comment by effbiae** [comment]
the l64 binary works on RHEL6.

**Comment by effbiae** [comment]
but embedpy expects to find python3 on the path and RHEL6 provides python36.
as a fix, create a symlink called python3 that points to /usr/bin/python3.6 and put it in your PATH.

**Comment by juanez** [comment]
the issue i had was that the library is compiled against a libc version which was unavailable to me. 
compiling from source solved it..
