### ISSUE TITLE
Installation fail on windows

### ISSUE THREAD

**Issue by mehditomas** [KxSystems/embedPy#63]
Hello,

When installing on windows, I run into this issue when running the tests or launching p.q:

```
'libpython
  [4]  C:\Users\Mehdi Tomas\Downloads\embedPy_windows-1.3.1\p.q:8:
 `L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
 .p:(`:./p 2:(`init;2))[L;H]]
    ^
  [0]  (<load>)
```
I get the same error if I try installing from a release or with Anaconda.

Sorry if I missed a step. I suspect this might have to do with my Python installation in Anaconda but I'm unsure. Thanks a lot for the help.

Specs:
- KDB+ 3.6,  64bit
- Python 3.6 64bit, Anaconda version

**Comment by Dianeod** [comment]
Hi,

What version of kdb+ are you using? You can find this with, .z.K and .z.k.

Thanks,
Diane

**Comment by mehditomas** [comment]
Hi Diane,

Versio 3.6.

**Comment by jhanna-kx** [comment]
Hi,
Haven't been able to replicate this so far. 
Could you list the versions of the conda packages you have installed?
```
conda list "python|kdb|embedpy"
```

And also the output from these two 
```
where q
where python3
```
Thanks

**Comment by jhanna-kx** [comment]
Also could you check if you have 32 bit or 64 bit python installed (embedPy requires 64 bit)
```
C:\Users\james>python -VV
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
C:\Users\james>echo p)print('embedPy')|q
embedPy

C:\Users\james>
```
Thanks

**Comment by mehditomas** [comment]
Hi James, I ran the queries you mentionned:

![image](https://user-images.githubusercontent.com/19539235/47510158-dc16f500-d877-11e8-8874-402b831274b6.png)

It seems I do have the 64 bit version of python.

**Comment by jhanna-kx** [comment]
Thanks for posting those, I'm not certain this is the issue, but it looks like there are a mixture of python installs on there with `python3` being non anaconda python, but `python`  and `q` being conda versions.

Could you remove the non anaconda `python3` from your PATH entirely and try running `q p.q`. 

The conda packaged version of embedPy probably won't work with the non anaconda python and `p.q` will first try to run `python3` before `python` . 

James

**Comment by elopezaguilera** [comment]
Closing this issue. Feel free to reopen if the previous solution hasn't solved the problem.
