### ISSUE TITLE
p) isn't showing the results for expressions

### ISSUE THREAD

**Issue by tepu** [KxSystems/embedPy#69]
If you run an expression in Python, it prints the result
```
>>> 1+2
3
```
but in embedpy, the result of an expression won't be printed unless you use print
```
q)p)1+2
q)p)print(1+2)
3
```

**Comment by jhanna-kx** [comment]
I think this is covered in https://github.com/KxSystems/embedPy/issues/8 ? 
`p)` uses `.p.e` which executes statements (so they can have side effects) these don't have results, if you want to evaluate an expression and get a result, you can use `.p.eval` instead. Feel free to reopen if you think I'm missing something
