### ISSUE TITLE
.p.eval errors on expressions containing assignments or function definitions

### ISSUE THREAD

**Issue by tepu** [KxSystems/embedPy#8]
```
q)p)x=2
```
will work as expected, but run
```
q).p.eval "x=2"
```
and you'll get the error
```
  File "<string>", line 1
    x=2
     ^
SyntaxError: invalid syntax
'p.c:68 runs pyerr
  [0]  .p.eval "x=2"
       ^
```
The same error is thrown when running an expression that defines a function
```
q).p.eval "def square(x): return x * x"
  File "<string>", line 1
    def square(x): return x * x
      ^
SyntaxError: invalid syntax
'p.c:68 runs pyerr
  [0]  .p.eval "def square(x): return x * x"
       ^
```

**Comment by abalkin** [comment]
Python differentiates between expressions and statements.  Variable assignments, function and class definitions are statements and `.p.eval`, which is similar to Python builtin `eval` does not work on these.  As far as I can tell, embedPy does not expose Python's `exec` to q yet.

Meanwhile, I see two work-arounds:

```q
.p.set[`x] .p.eval"42"
```

or

```
q).p.eval"exec('x=42')"
```

**Comment by jhanna-kx** [comment]
To do this I think you'll need to use `.p.e. not `.p.eval`

 .p.eval and p.e (used when prefixing code with `p)`) run the PyRun_String C API function internally, the difference is that .p.e run's it with `Py_file_input` allowing multiple expressions with side effects but not returning any value and .p.eval uses `Py_eval_input` which returns a value but is not allowed to have side effects. 

`.p.e` is analogous to python's exec
`.p.eval/pyeval` are analogous to python eval
```python
>>> eval('x=2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    x=2
     ^
SyntaxError: invalid syntax
>>> y=exec('z=10')
>>> print(y,z)
None 10
```

There's a longer explanation at the link below here https://stackoverflow.com/questions/2220699/whats-the-difference-between-eval-exec-and-compile-in-python

**Comment by tepu** [comment]
Great explanation, thank you. It would be helpful if the difference between .p.e and .p.eval was mentioned in the readme.

**Comment by jhanna-kx** [comment]
Thanks, we'll add a note to the README for this
