### ISSUE TITLE
embedPy

### ISSUE THREAD

**Issue by thxx1138** [KxSystems/embedPy#84]
q)\l p.q
'libpython
  [3]  M:\q\p.q:9:
 `L`M`H`B set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];C:H~B;
 .p:(`:./p 2:(`init;3))[L;H;C]]
    ^

When I do at this point : <b>key each hsym each`$`L`M#.p</b>     I will get:

L| `:C:\Users\serge\AppData\Local\Programs\Python\Python38-32/python38.dll

M| `q`Q`h`j`o`P`p

PS: Hint: I only used the downloaded code in that link under "embedPy"  --> no conda installation

**Comment by cmccarthy1** [comment]
Can you please point to the exact instructions that you followed to complete the install?

It appears that you install has been somehow corrupted (the value for `M` in your evaluation should also point to a file location). 

As you may have seen [here](https://code.kx.com/q/ml/embedpy/faq/). This issue arises usually when the install of Python does not have access to the Python shared object.

**Comment by thxx1138** [comment]
In the overview page under “Build and install” it is mentioned “Download the from KxSystems/embedPy” and follow installation there … so I downloaded the zipped code and unzipped into my Q directory. But I did not see any “installation instructions” … so I was assuming it is enough to start Kdb+ and load the p.q script

 

Btw: I use Windows 10 / 64-bit and Q version 3.7t

**Comment by cmccarthy1** [comment]
Ok, thanks! 

Could you check that unzipping resulted in the `p.dll` file being populated in your `%QHOME%/w64` directory?

**Comment by thxx1138** [comment]
Yes, its all in w64 – also the p.dll

**Comment by thxx1138** [comment]
Well. My QHOME includes w64, as the q executable is also there

 

From:  <milan_ondrus@hispeed.ch> 
Sent: Montag, 23. März 2020 19:04
To: 'KxSystems/embedPy' <reply@reply.github.com>
Subject: RE: [KxSystems/embedPy] embedPy (#84)

 

Yes, its all in w64 – also the p.dll

**Comment by thxx1138** [comment]
One issue I found ... the Environment variable LD_LIBRARY_PATH was missing 

 

Now I get the following error:

 

'Das angegebene Modul wurde nicht gefunden.

  [3]  M:\q\w64\p.q:9:

`L`M`H`B set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];C:H~B;

.p:(`:./p 2:(`init;3))[L;H;C]]

 

That German text there means “That Module was not found”

The values:

 

L is "C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python38-32/python38.dll"

M is "" 

B and H are both: "C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python38-32"

C is 1b

**Comment by cmccarthy1** [comment]
By the look of the code I don't think you're using the same `p.q` that was in the zipped file [here](https://github.com/KxSystems/embedPy/releases)?

Support was added for users using virtual environments [here](https://github.com/KxSystems/embedPy/pull/81) and this code has the addition of the C parameter you're highlighting. This should not have been in the zipped directory?

**Comment by thxx1138** [comment]
But in that  “embedPy-1.3.2.zip” I don’t see the p.dll

**Comment by cmccarthy1** [comment]
At this address https://github.com/KxSystems/embedPy/releases within this folder embedPy_windows-1.3.2.zip the `p.dll` will be in the w64 folder in the unzipped file. This should  be added to your `%QHOME%/w64` and the contents in the root of that file added to your `%QHOME%` directory

**Comment by cmccarthy1** [comment]
@thxx1138 Did you get this fixed?

**Comment by cmccarthy1** [comment]
Closing this for now as I believe the instructions are sufficient to fix, if you're still having issues please reopen
