### ISSUE TITLE
Missing p.so

### ISSUE THREAD

**Issue by simonsjw** [KxSystems/embedPy#89]
Hi - this repo appears to be missing the q.so file formally in a folder l64.
The installation instructions still appear to reference the file. 
Also the instructions reference running q test.q before installing embedPy. 
Regards,
Simon

**Comment by dmorgankx** [comment]
Hi Simon,

I assume you're referring to the p.so file.

If you're installing a release, the p.so file will be contained in l64 directory within the latest Linux release - https://github.com/KxSystems/embedPy/releases/tag/1.3.4 .

If you're cloning the repo and building from source, the below command will generate p.so and run the tests:

```
$ make p.so && q test.q
```

For both methods, you'll need to move p.q and p.k to $QHOME and p.so to $QHOME/l64.

I hope this helps. If you have any further issues, please let us know.

Thanks,
Deanna

**Comment by simonsjw** [comment]
Ok - thanks Deanna 
Maybe my mistake.
Simon
