### ISSUE TITLE
embedPy test gives "The specified module could not be found"

### ISSUE THREAD

**Issue by kamchan0** [KxSystems/embedPy#92]
Trying to follow the step in the installation guide for Windows. Extracted the embedPy zip and ran
`pip install -r tests/requirements.txt`

then got an error when running `q test.q`

```
C:\Users\xxxx\Downloads\embedPy_windows-1.3.6>q test.q
KDB+ 3.6 2019.09.19 Copyright (C) 1993-2019 Kx Systems
w64/ 8(16)core 16275MB xxxx xxxx 192.168.0.14 EXPIRE 2021.03.16 xxxx@gmail.com KOD #4169673

'The specified module could not be found.
  [4]  C:\Users\xxxx\Downloads\embedPy_windows-1.3.6\p.q:12:
 `L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
 .p:(`:./p 2:(`init;2))[L;H]]
           ^
  [0]  (<load>)

  )
  )key each hsym each`$`L`M#.p
'each
  [5]  key each hsym each`$`L`M#.p
                     ^
  )
  )  )'2020.07.26T09:57:04.146 .Q.dbg
```

**Comment by cmccarthy1** [comment]
Hi @kamchan0 

The error `'The specified module could not be found.` indicates that the interface was unable to find the required `p.dll` which the interface links to. Please ensure that the `p.dll` located within the `w64` folder of your extracted `.zip` file has been placed in your `%QHOME/w64` directory and rerun the test script.

All the best,

Conor

**Comment by cmccarthy1** [comment]
Hi @kamchan0 

Closing this issue for now as I believe the above response adequately covers the error you had been seeing. Please reopen the issue and provide more information is there are any further concerns.

All the best,

Conor
